Serialization WIP
manio143/ShadowsOfShadows pull request #51
Opened 2017-05-23 09:06 UTC by michal17

2017-05-23 09:09 UTC, dkaluza commented on src/Consoles/MainConsole.cs
> +            //Example of loading game state from file
Wyrzucić do odzielnej  metody pobierającej odpowiedni argument(nazwa_sava, czy też slot)

2017-05-23 09:45 UTC, dkaluza requested changes

2017-05-23 09:45 UTC, dkaluza commented on src/Consoles/MainConsole.cs
> +
zapisywanie też w odzielnej metodzie

2017-05-23 09:45 UTC, dkaluza commented on src/Entities/Entity.cs
> +        /* For serialization */
Przypisywanie char w konstruktorze, który zostaje przekazany przez konstruktory bezparametrowe podklas

2017-05-23 09:45 UTC, dkaluza commented on src/Entities/Entity.cs
> +        public abstract char GetEntityChar();
Do usunięcia

2017-05-23 09:45 UTC, dkaluza commented on src/Entities/Entity.cs
> -	public abstract class Entity
Dodanie atrybutu serializable

2017-05-23 09:45 UTC, dkaluza commented on src/Entities/Player.cs
> +                return list.ToArray();
Ponoć bezsensu

2017-05-23 11:09 UTC, manio143 requested changes

2017-05-23 11:09 UTC, manio143 commented on src/Consoles/MainConsole.cs
> +            GameObject playerObject = Player.Renderable.ConsoleObject;
Będę jednak za tym aby zostawić `var` wszędzie gdzie to możliwe.

2017-05-23 11:09 UTC, manio143 commented on src/Items/Consumable.cs
> +    [System.Xml.Serialization.XmlInclude(typeof(RegenerationConsumable))]
Zobacz https://social.msdn.microsoft.com/Forums/en-US/83181d16-a048-44e5-b675-a0e8ef82f5b7/why-do-i-have-to-xmlinclude-derived-classes-in-order-to-serialize?forum=asmxandxml
robienie tych `[XmlInclude]` jest nadmiarowe.

2017-05-23 11:09 UTC, manio143 commented on src/Physics/CollisionBox.cs
> +
Jeśli już tworzysz puste konstruktory to niech zajmują tylko jedną linijkę
`public CollisionBox() { }`

2017-05-23 11:09 UTC, manio143 commented on src/Serialization/GameState.cs
> +			XmlSerializer xsSubmit = new XmlSerializer(typeof(GameState));
Tutaj dodaj potrzebne namespace'y, jako drugi argument `XmlSerializer`

2017-05-23 11:09 UTC, manio143 commented on src/Serialization/GameState.cs
> +					xsSubmit.Serialize(writer, objectToSerialize);
Wydaje mi się, że nie ma potrzeby tworzyć lokalnej zmiennej mapującej na `this`. Natomiast ja bym logikę zapisywania wyniósł do osobnej statycznej klasy. Metoda `Save()`, najlepiej żeby brała `enum SaveSlot { Slot1, Slot2, Slot3, Slot4 }` i `GameState`.

2017-05-23 11:09 UTC, manio143 commented on src/Serialization/GameState.cs
> +        public GameState loadGameState(string fileName)
Analogicznie jak wyżej, do statycznej klasy

2017-05-23 11:09 UTC, manio143 commented on src/ShadowsOfShadows.csproj
> +      <HintPath>packages\MonoGame.Framework.DesktopGL.3.5.1.1679\lib\net40\MonoGame.Framework.dll</HintPath>
Trzeba ręcznie usunąć te zmiany dot. wersji w `Include=` bo to nam ogranicza aplikację. Jak tego nie ma, to można kompilować z dowolną wersją biblioteki.

2017-05-23 11:09 UTC, manio143 commented on src/ShadowsOfShadows.csproj
> -    <Folder Include="Entities\" />
Jeśli nie ma potrzeby to bym tego nie usuwał. Wiem, że prawdopodobnie IDE ci to zrobiło automatycznie, ale lepiej to cofnąć.
Zapoznaj się z poleceniem `git rebase -i` oraz `git add -p` ;)

2017-05-23 11:09 UTC, manio143 commented on savedgames/1.sav
> +<?xml version="1.0" encoding="utf-16"?><GameState xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"><Player><Transform><Position><X>1</X><Y>1</Y></Pos
Nie chcemy dodawać save'ów do repo

2017-05-23 11:09 UTC, manio143 commented on src/Entities/Player.cs
> +                return list.ToArray();
`Dictionary<K, V>` ma atrybut `[Serializable]`

2017-05-23 11:09 UTC, manio143 commented on src/Renderables/ConsoleRenderable.cs
> +    [Serializable]
Wydaje mi się, że `ConsoleRenderable` nie powinien być serializowany, wręcz ignorujmy go w Entity

2017-05-23 11:09 UTC, manio143 commented on src/Renderables/IRenderable.cs
> +    [System.Xml.Serialization.XmlInclude(typeof(ConsoleRenderable))]
Zobacz komentarz pod Implementacją tego interfejsu

2017-05-28 17:44 UTC, manio143 commented on src/Entities/Projectile.cs
> +        public Projectile() : base('O') { }
Sugerowalbym gwiazdkę (*) ;)

2017-05-28 17:47 UTC, manio143 commented on src/Renderables/IRenderable.cs
>          [XmlIgnore]
Skoro nie serializujemy `IRenderable` to i tegi atrybutu nam nie potrzeba.

2017-05-28 17:53 UTC, manio143 commented on src/Serialization/Serializer.cs
> +                    typeof(Wall), typeof(Chest)}); // TODO Is it necessary to list all the types here?
Można pójść na łatwiznę i zrobić coś takiego:
```
var xmlTypes = Assembly.GetAssembly(this.GetType())
               .GetTypes().ToArray();
```

2017-05-28 17:55 UTC, manio143 commented on src/Serialization/Serializer.cs
> +            {
Jeśli mamy dwa usingi jeden pod drugim to można opuścić klamry

2017-05-28 18:07 UTC, manio143 commented on src/Serialization/Serializer.cs
> +                    System.IO.StreamWriter file = new System.IO.StreamWriter("../../../savedgames/" + slot + ".sav");
Czemu idziemy `../../../`? W momencie kiedy gra opuści nasz folder `bin/Debug` to będziemy chcieli żeby save'y siedziały np. w folderze domowym użytkownika.

Wyciągnij ten początkowy string do pola `private static string SaveFolder` i można zrobić 
```
private static string SaveFolder = Path.Combine(
                        Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData)),
                        "ShadowsOfShadows",
                        "savedgames");
```

2017-05-28 18:08 UTC, manio143 approved these changes

2017-05-29 20:46 UTC, michal17 commented on src/Serialization/Serializer.cs
> +                    typeof(Wall), typeof(Chest)}); // TODO Is it necessary to list all the types here?
Nie działa dla klas które nie są publiczne albo nie mają bezparametrowego konstruktora :(

2017-05-30 04:19 UTC, manio143 commented
Żeby deserializacja działała, to albo trzeba napisać nasz własny system, który będzie konstruował obiekty z odpowiednimi parametrami, albo żeby użyć uniwersalnego deserializera to musimy dostarczyć bezparametrowe konstruktory i publiczne settery.

2017-05-30 09:57 UTC, dkaluza approved these changes

2017-06-02 14:49 UTC, merged